from typing import Optional, Sequence

from .MPI import Intracomm

def helloworld(comm: Intracomm, args: Optional[Sequence[str]] = None, verbose: bool = True) -> str: ...
def ringtest(comm: Intracomm, args: Optional[Sequence[str]] = None, verbose: bool = True) -> float: ...
def main(args: Optional[Sequence[str]] = ...) -> None: ...
