#!/bin/bash

sudo chmod -R 755 /sys/class/powercap/intel-rapl/

constants_file_path="/home/yimoning/research/util/constants.py"

for ((i=1; i<50; i++)); do
  for ((j=1; j<50; j++)); do

    FILE_NAME="${i}*${i}_${j}times.csv"

    # Overwrite the constants.py file with new values
    cat > $constants_file_path << EOF
CELLSIZE = $i
SIMROUND = $j
FILE_NAME = "$FILE_NAME"
EOF

    begin_time=$(date +%s)
    python3 /home/yimoning/research/pydevs/pyjoulse_test/first_demo.py &
    PID1=$!

    echo "process starts with CELLSIZE=$i, SIMROUND=$j"
    echo "Starting sleep"
    sleep 10
    echo "Sleep finished, starting SIR_test.py"

    start_time=$(date +%s)
    python3 /home/yimoning/research/pydevs/PythonPDEVS-master/pythonpdevs/examples/SIR_test.py &
    PID2=$!

    echo "waiting for sim running"
    wait $PID2

    end_time=$(date +%s)
    real_start=$((start_time - begin_time))
    real_end=$((end_time - begin_time))

    echo "sim has finished"
    echo "---- cool down -----"
    wait $PID1

  done
done
